import os

SCREEN_RESOLUTION = (640, 480)
WINDOWS_CAPTION = 'CRINGEtris v.0.1'
SPEED_LEVELS = [15, 13, 11, 9, 7, 5, 3, 1]
DATA_FOLDER = 'data'
MENU_FONT_NAME = 'Arial'
MENU_FONT_SIZE = 90
SPEED_LABEL_FONT_SIZE = 36
SCORES_LABEL_FONT_SIZE = 48
MAX_FPS = 60
LOG_LEVEL = 'DEBUG'
MAIN_DIR = os.path.split(os.path.abspath(__file__))[0]
